/* Serialized into the publication. It deliberately has no imports or network behavior. */
export function clientRuntime(model: any): void {
  "use strict";
  const get = (id: string) => document.getElementById(id)!;
  const ui = new Map(model.ui.tokens.map((token: any) => [token.id, token.text ?? token.template]));
  const areaValues = model.authority.vocabularies.rules_areas;
  const areas: Map<string,any> = new Map(areaValues.map((value: any) => [value.id, value]));
  const entities: Map<string,any> = new Map(model.authority.entities.map((entity: any) => [entity.id, entity]));
  const categories: Map<string,any> = new Map(model.authority.navigation.categories.map((category: any) => [category.id, category]));
  const calculator=model.authority.calculator;
  const calculatorFeatures:Map<string,any>=new Map(calculator.features.map((feature:any)=>[feature.entity_id,feature]));
  const defaultCalculatorSelection=String(calculator.default_feature_id);
  const indexed = model.filterIndex.entities;
  const indexedById:Map<string,any>=new Map(indexed.map((item:any)=>[item.id,item]));
  const state: any = { view: "home", category: model.authority.navigation.default_category_id, topic: "", classifications: {}, entity: null, resultRoute: null, calculatorSelection:defaultCalculatorSelection, fighterLevel:calculator.default_fighter_level, psiModifier:calculator.default_psionic_ability_modifier, focusOrigin: "fragment" };
  const homeFragment=String(model.policy.home_fragment);
  const calculatorFragment=String(model.policy.calculator_fragment);
  const category = () => categories.get(state.category) as any;
  const categoryTopics = (categoryId=state.category) => [...(categories.get(categoryId)?.topics ?? [])].sort((a:any,b:any)=>a.order-b.order);
  const defaultTopic = (categoryId=state.category) => categories.get(categoryId)?.default_topic_id??categoryTopics(categoryId)[0]?.id??"";
  const topic = () => categoryTopics().find((item: any) => item.id === state.topic);
  function normalizeNavigation(requestedCategory:any=state.category,requestedTopic:any=state.topic):boolean {
    const nextCategory=typeof requestedCategory==="string"&&categories.has(requestedCategory)?requestedCategory:model.authority.navigation.default_category_id;
    const options=categoryTopics(nextCategory);const requestedIsValid=typeof requestedTopic==="string"&&options.some((item:any)=>item.id===requestedTopic);
    const nextTopic=requestedIsValid?requestedTopic:defaultTopic(nextCategory);let corrected=nextCategory!==requestedCategory||nextTopic!==requestedTopic;
    state.category=nextCategory;state.topic=nextTopic;
    if(state.entity){if(!topic()?.entity_ids.includes(state.entity)){state.entity=null;state.resultRoute=null;corrected=true;}else if(corrected)state.resultRoute=state.topic;}
    return corrected;
  }
  const match = (item: any, selections = state.classifications) => Object.entries(selections).every(([facet, raw]: any) => {
    const values = Array.isArray(raw) ? raw : raw ? [raw] : [];
    return values.length === 0 || values.some((value: string) => item.classifications[facet]?.includes(value));
  });
  const matches = () => indexed.filter((item: any) => match(item));
  const hasSelections = () => Object.values(state.classifications).some((value: any) => Array.isArray(value) ? value.length : Boolean(value));
  const isMobile = () => typeof matchMedia === "function" && matchMedia("(max-width: 760px)").matches;
  const safeState = () => ({ view: state.view, category: state.category, topic: state.topic, classifications: structuredClone(state.classifications), entity: state.entity, resultRoute: state.resultRoute, calculatorSelection:state.calculatorSelection, fighterLevel:state.fighterLevel, psiModifier:state.psiModifier, focusOrigin: state.focusOrigin });
  const referenceFragment = (categoryId=state.category,topicId=state.topic,classifications:any=state.classifications,entityId:string|null=state.entity) => {
    const parameters = new URLSearchParams(); parameters.set("category", categoryId); parameters.set("topic", topicId);
    const filters = Object.entries(classifications).filter(([,value]: any) => Array.isArray(value) ? value.length : value).map(([facet,value]: any) => `${facet}:${(Array.isArray(value)?value:[value]).join(",")}`).join(";");
    if (filters) parameters.set("filters", filters); if (entityId) parameters.set("entity", entityId);
    return `#${parameters.toString()}`;
  };
  const fragment = () => state.view==="home"?`#${homeFragment}`:state.view==="calculator"?`#${calculatorFragment}`:referenceFragment();
  const writeHistory = (mode: "push"|"replace") => history[mode === "push" ? "pushState" : "replaceState"](safeState(), "", fragment());
  const ordinaryActivation = (event:MouseEvent) => !event.defaultPrevented&&event.button===0&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey;
  function syncNameSelection(): void { const select=get("name-select") as HTMLSelectElement;select.value=state.entity&&indexedById.has(state.entity)?state.entity:""; }
  function announce(message: string): void {
    const region=get("filter-live"); get("filter-root").setAttribute("data-filter-settled","false"); region.textContent="";
    queueMicrotask(()=>{region.textContent=message;get("filter-root").setAttribute("data-filter-settled","true");});
  }
  function renderNavigation(): void {
    const categorySelect=get("category-select") as HTMLSelectElement; categorySelect.textContent="";
    for(const item of [...categories.values()].sort((a:any,b:any)=>a.order-b.order)){const option=document.createElement("option");option.value=item.id;option.textContent=item.label;categorySelect.append(option);}
    categorySelect.value=state.category;
    const topicSelect=get("topic-select") as HTMLSelectElement;topicSelect.textContent="";
    for(const item of categoryTopics()){const option=document.createElement("option");option.value=item.id;option.textContent=item.title;topicSelect.append(option);}
    topicSelect.value=state.topic;
  }
  const appendInline = (parent: HTMLElement, node: any) => {
    const element=node.type==="strong"?document.createElement("strong"):node.type==="emphasis"?document.createElement("em"):node.type==="code"?document.createElement("code"):document.createElement("span");
    element.textContent=node.text??node.label??String(node.value?.value??"");parent.append(element);
  };
  const inlineText = (nodes:any[]) => nodes.map(node=>node.text??node.label??String(node.value?.value??"")).join("");
  const inlineSlice = (nodes:any[],start:number,end:number) => {const result:any[]=[];let offset=0;for(const node of nodes){const value=node.text??node.label??String(node.value?.value??"");const from=Math.max(start-offset,0),to=Math.min(end-offset,value.length);if(from<to)result.push({...node,text:value.slice(from,to),label:undefined,value:undefined});offset+=value.length;}return result;};
  const trimInlineRange = (text:string,start:number,end:number) => {while(start<end&&/\s/.test(text[start]!))start++;while(end>start&&/\s/.test(text[end-1]!))end--;return [start,end] as const;};
  const appendParagraph = (parent:HTMLElement,nodes:any[]) => {const paragraph=document.createElement("p");nodes.forEach((node:any)=>appendInline(paragraph,node));parent.append(paragraph);};
  const appendFeatureTier = (parent:HTMLElement,labelText:string,body:(content:HTMLElement)=>void,tier?:number) => {const tierElement=document.createElement("section");tierElement.className="feature-tier";if(tier!==undefined)tierElement.dataset.tier=String(tier);const label=document.createElement("h3");label.className="feature-tier__label";label.textContent=labelText;const content=document.createElement("div");content.className="feature-tier__content";body(content);tierElement.append(label,content);parent.append(tierElement);};
  function renderTierParagraph(parent:HTMLElement,block:any):boolean {const text=inlineText(block.inlines);const matches=[...text.matchAll(/(^|\s)(T(\d+) (?:Base|Overload)):\s*/g)];if(!matches.length)return false;const first=matches[0]!,prefixEnd=first.index??0;const [prefixStart,prefixTrimmedEnd]=trimInlineRange(text,0,prefixEnd);if(prefixStart<prefixTrimmedEnd)appendParagraph(parent,inlineSlice(block.inlines,prefixStart,prefixTrimmedEnd));matches.forEach((match,index)=>{const next=matches[index+1];const start=(match.index??0)+match[0].length,end=next?.index??text.length;const [trimmedStart,trimmedEnd]=trimInlineRange(text,start,end);appendFeatureTier(parent,match[2]!,content=>appendParagraph(content,inlineSlice(block.inlines,trimmedStart,trimmedEnd)),Number(match[3]));});return true;}
  const referenceCountMessage=(visible:number,total:number):string=>String(ui.get("reference_showing_count")).replace("{visible_count}",String(visible)).replace("{total_count}",String(total));
  function updateReferenceFilter(rows:HTMLTableRowElement[],show:HTMLSelectElement,level:HTMLSelectElement,count:HTMLElement,noMatches:HTMLElement,live:HTMLElement,root:HTMLElement,shouldAnnounce:boolean):void {let visible=0;for(const row of rows){const matches=(!show.value||row.dataset.referenceGroup===show.value)&&(!level.value||row.dataset.referenceLevel===level.value);row.classList.toggle("reference-row--filtered",!matches);if(matches)visible++;}const countMessage=referenceCountMessage(visible,rows.length),message=visible?countMessage:`${String(ui.get("reference_no_matches"))} ${countMessage}`;count.textContent=countMessage;noMatches.hidden=visible!==0;if(!shouldAnnounce)return;root.dataset.referenceFilterSettled="false";live.textContent="";queueMicrotask(()=>{live.textContent=message;root.dataset.referenceFilterSettled="true";});}
  function appendReferenceFilters(parent:HTMLElement,table:HTMLTableElement,rows:HTMLTableRowElement[]):void {
    const showOptions=[["","reference_show_all"],["common_features","reference_show_common"],["pyrokinesis","reference_show_pyrokinesis"],["cryokinesis","reference_show_cryokinesis"],["psychokinesis","reference_show_psychokinesis"],["electrokinesis","reference_show_electrokinesis"],["advanced_training","reference_show_advanced_training"]] as const;
    const levelValues=["","3rd","5th","7th","10th","15th","18th","20th","15th+","18th+"] as const;
    const makeField=(id:string,labelText:string)=>{const label=document.createElement("label");label.className="field reference-filter__field";label.htmlFor=id;label.append(document.createTextNode(labelText));const select=document.createElement("select");select.id=id;select.setAttribute("aria-controls",table.id);label.append(select);return{label,select};};
    const show=makeField("reference-show",String(ui.get("reference_show_label"))),level=makeField("reference-level",String(ui.get("reference_level_label")));for(const [value,tokenId] of showOptions){const option=document.createElement("option");option.value=value;option.textContent=String(ui.get(tokenId));show.select.append(option);}for(const value of levelValues){const option=document.createElement("option");option.value=value;option.textContent=value||String(ui.get("reference_level_all"));level.select.append(option);}
    const root=document.createElement("div");root.className="reference-filters";root.dataset.referenceFilterSettled="true";
    const feedback=document.createElement("div");feedback.className="reference-filter__feedback";const count=document.createElement("p");count.id="reference-filter-count";count.className="reference-filter__count";const noMatches=document.createElement("p");noMatches.id="reference-filter-no-matches";noMatches.className="reference-filter__empty";noMatches.textContent=String(ui.get("reference_no_matches"));noMatches.hidden=true;const live=document.createElement("div");live.id="reference-filter-live";live.className="sr-only";live.setAttribute("role","status");live.setAttribute("aria-live","polite");live.setAttribute("aria-atomic","true");feedback.append(count,noMatches,live);
    root.append(show.label,level.label,feedback);table.setAttribute("aria-describedby",count.id);parent.append(root);
    const update=(announce:boolean)=>updateReferenceFilter(rows,show.select,level.select,count,noMatches,live,root,announce);show.select.addEventListener("change",()=>update(true));level.select.addEventListener("change",()=>update(true));update(false);
  }
  function renderBlock(parent: HTMLElement, block: any): void {
    if(block.type==="example_play_section"){const section=document.createElement("section");section.className=`example-play-section example-play-section--${block.discipline}`;section.dataset.discipline=block.discipline;const heading=document.createElement("h3");heading.className="example-play-section__heading";heading.id=`example-play-${block.discipline}-${inlineText(block.title).toLowerCase().replaceAll(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`;block.heading.forEach((node:any)=>appendInline(heading,node));section.setAttribute("aria-labelledby",heading.id);const content=document.createElement("div");content.className="example-play-section__content";const title=document.createElement("h4");title.className="example-play-section__title";block.title.forEach((node:any)=>appendInline(title,node));const body=document.createElement("div");body.className="example-play-section__body";for(const [field,label] of [["setup","Setup"],["activation","Activation"],["rolls_or_saves","Rolls or Saves"],["damage","Damage"],["effects","Effects"],["result","Result"]] as const){const phase=document.createElement("section");phase.className=`example-play-section__phase example-play-section__phase--${field.replaceAll("_","-")}`;const phaseTitle=document.createElement("h5");phaseTitle.className="example-play-section__phase-title";phaseTitle.textContent=label;phase.append(phaseTitle);block[field].forEach((phaseBlock:any)=>renderBlock(phase,phaseBlock));body.append(phase);}content.append(title,body);section.append(heading,content);parent.append(section);return;}
    if(block.type==="example"){const aside=document.createElement("aside");aside.className="inline-example";aside.dataset.overloadTier=String(block.tier);const title=document.createElement("h3");title.className="inline-example__title";block.title.forEach((node:any)=>appendInline(title,node));const body=document.createElement("div");body.className="inline-example__body";block.body.forEach((child:any)=>renderBlock(body,child));aside.append(title,body);parent.append(aside);return;}
    if(block.type==="tier"){appendFeatureTier(parent,`T${block.tier} ${inlineText(block.heading)}`,content=>block.body.forEach((child:any)=>renderBlock(content,child)),block.tier);return;}
    if(block.type==="paragraph"||block.type==="note"){if(block.type==="paragraph"&&renderTierParagraph(parent,block))return;const element=document.createElement(block.type==="note"?"aside":"p");if(block.type==="note")element.className=`note ${block.kind}`;block.inlines.forEach((node:any)=>appendInline(element,node));parent.append(element);return;}
    if(block.type==="list"){const list=document.createElement(block.style==="ordered"?"ol":"ul");for(const item of block.items){const li=document.createElement("li");item.forEach((node:any)=>appendInline(li,node));list.append(li);}parent.append(list);return;}
    if(block.type==="table"){const wrapper=document.createElement("div");wrapper.className="table-scroll";wrapper.tabIndex=0;const table=document.createElement("table");if(block.row_references||block.headers.some((cell:any)=>inlineText(cell)==="Ongoing Duration"))table.className="quick-reference-table";const thead=document.createElement("thead");const headerRow=document.createElement("tr");
      for(const cell of block.headers){const th=document.createElement("th");th.scope="col";cell.forEach((node:any)=>appendInline(th,node));headerRow.append(th);}thead.append(headerRow);table.append(thead);const tbody=document.createElement("tbody");
      for(const [rowIndex,row] of block.rows.entries()){const tr=document.createElement("tr"),reference=block.row_references?.[rowIndex];if(reference){const referencedEntity="entity_id" in reference?entities.get(reference.entity_id):undefined,group=referencedEntity?.presentation_metadata.primary_rules_area??reference.reference_group;tr.dataset.referenceGroup=group;tr.dataset.referenceLevel=reference.reference_level;if(referencedEntity)tr.dataset.referenceEntity=referencedEntity.id;}for(const cell of row){const td=document.createElement("td");cell.forEach((node:any)=>appendInline(td,node));tr.append(td);}tbody.append(tr);}table.append(tbody);wrapper.append(table);if(block.row_references){table.id="psi-cost-reference-table";appendReferenceFilters(parent,table,[...tbody.rows]);}parent.append(wrapper);}
  }
  const activationDisplay = (entity:any):string => {
    if(entity.id==="common_manifested_strike")return "Attack action · Replaces an attack";
    if(entity.id==="common_empathic_sense")return "Passive · Bonus Action scan";
    if(entity.classifications.feature_role==="rider")return "Declared before roll · Resolves on hit";
    return ({action:"Action",bonus_action:"Bonus Action",reaction:"Reaction",passive:"Passive"} as Record<string,string>)[entity.activation]??"Special";
  };
  function renderTopic(focusEntity?: string,focusMode:"none"|"result"|"mobile"="none"): void {
    normalizeNavigation();const main=get("rules-content");main.textContent="";const current=topic();if(!current)return;
    for(const entityId of current.entity_ids){const entity=entities.get(entityId) as any;const article=document.createElement("article");article.id="entity-"+entity.id;const heading=document.createElement("h2");heading.textContent=entity.title;heading.tabIndex=-1;heading.dataset.sourcePath="entities."+entity.id+".title";article.append(heading);
      const activation=entity.activation===undefined?undefined:activationDisplay(entity);
      if(entity.level!==undefined||entity.psi_cost!==undefined||activation!==undefined||entity.requires_concentration===true){const dl=document.createElement("dl");dl.className="facts feature-metadata";for(const [tokenId,value] of [["fact_level",entity.level],["fact_psi",entity.psi_cost],["fact_activation",activation],["fact_duration",entity.concentration_duration]])if(value!==undefined){const item=document.createElement("div");item.className="feature-metadata__item";const dt=document.createElement("dt");dt.textContent=String(ui.get(tokenId));const dd=document.createElement("dd");dd.textContent=String(value);item.append(dt,dd);dl.append(item);}if(entity.requires_concentration===true){const item=document.createElement("div");item.className="feature-metadata__item feature-metadata__item--concentration";const dt=document.createElement("dt");dt.className="sr-only";dt.textContent=String(ui.get("fact_requirement"));const dd=document.createElement("dd");dd.textContent=String(ui.get("fact_concentration"));item.append(dt,dd);dl.append(item);}article.append(dl);}
      if(entity.content.every((block:any)=>block.type==="example_play_section")){const sections=document.createElement("div");sections.className="example-play-flow";entity.content.forEach((block:any)=>renderBlock(sections,block));article.append(sections);}else entity.content.forEach((block:any)=>renderBlock(article,block));main.append(article);}
    const heading=(focusEntity?document.querySelector("#entity-"+CSS.escape(focusEntity)+" h2"):main.querySelector("article h2")) as HTMLElement|null;const mobile=isMobile();
    if(heading&&(focusMode==="result"||(focusMode==="mobile"&&mobile))){if(mobile){heading.focus({preventScroll:true});heading.scrollIntoView({block:"start"});}else heading.focus();}
  }
  const canonicalText=(element:HTMLElement,text:string,path:string)=>{element.textContent=text;element.dataset.sourcePath=path;return element;};
  const appendCanonicalParagraph=(parent:HTMLElement,text:string,path:string,className?:string)=>{const paragraph=canonicalText(document.createElement("p"),text,path);if(className)paragraph.className=className;parent.append(paragraph);return paragraph;};
  const focusHeading=(heading:HTMLElement|null)=>{if(!heading)return;heading.focus({preventScroll:true});if(typeof heading.scrollIntoView==="function")heading.scrollIntoView({block:"start"});};
  function syncViewChrome():void {const home=state.view==="home",calculatorView=state.view==="calculator",reference=state.view==="reference",main=document.querySelector<HTMLElement>("main.layout")!,controls=document.querySelector<HTMLElement>("aside.controls")!,content=get("rules-content"),startLink=get("view-start-here"),referenceLink=get("view-rules-reference"),calculatorLink=get("view-calculator");controls.hidden=!reference;main.dataset.view=state.view;main.classList.toggle("layout--home",home);main.classList.toggle("layout--reference",reference);main.classList.toggle("layout--calculator",calculatorView);content.classList.toggle("home",home);content.classList.toggle("rules",reference);startLink.setAttribute("href",`#${homeFragment}`);referenceLink.setAttribute("href",referenceFragment());calculatorLink.setAttribute("href",`#${calculatorFragment}`);for(const [link,active] of [[startLink,home],[referenceLink,reference],[calculatorLink,calculatorView]] as const)if(active)link.setAttribute("aria-current","page");else link.removeAttribute("aria-current");}
  function categoryHref(categoryId:string):string {const target=categories.get(categoryId);return target?referenceFragment(target.id,target.default_topic_id,{},null):referenceFragment(model.authority.navigation.default_category_id,defaultTopic(model.authority.navigation.default_category_id),{},null);}
  function entityHref(entityId:string):string {const item=indexedById.get(entityId);if(!item)return categoryHref(model.authority.navigation.default_category_id);const area=item.primary_rules_area;return referenceFragment(area,item.routes[area],{},entityId);}
  function focusOnboardingSection(sectionId:string):void {const section=document.getElementById(sectionId),heading=section?.querySelector<HTMLElement>(":scope > h3")??null;focusHeading(heading);}
  function destinationControl(link:any,path:string):HTMLButtonElement|HTMLAnchorElement {const destination=link.destination;let control:HTMLButtonElement|HTMLAnchorElement;if(destination.kind==="onboarding_section"){const button=document.createElement("button");button.type="button";button.addEventListener("click",()=>focusOnboardingSection(destination.section_id));control=button;}else{const anchor=document.createElement("a");anchor.href=destination.kind==="category"?categoryHref(destination.category_id):entityHref(destination.entity_id);anchor.addEventListener("click",event=>{if(!ordinaryActivation(event))return;event.preventDefault();if(destination.kind==="category")openCategory(destination.category_id);else openEntity(destination.entity_id,"onboarding");});control=anchor;}canonicalText(control,link.title,path+".title");control.dataset.onboardingLinkId=link.id;control.dataset.destinationKind=destination.kind;return control;}
  function appendDestinationList(parent:HTMLElement,links:any[],path:string):void {const list=document.createElement("ul");list.className="home-links";links.forEach((link,index)=>{const item=document.createElement("li");item.append(destinationControl(link,`${path}.${index}`));list.append(item);});parent.append(list);}
  function homeSection(section:any,path:string):HTMLElement {const element=document.createElement("section");element.id=section.id;element.className="home-section";element.dataset.onboardingId=section.id;const heading=canonicalText(document.createElement("h3"),section.title,path+".title");heading.id=section.id+"_heading";heading.tabIndex=-1;element.append(heading);return element;}
  function renderHome(focusPage=false):void {
    const onboarding=model.authority.onboarding;syncViewChrome();const root=get("rules-content");root.textContent="";
    const guide=document.createElement("div");guide.className="home-guide";guide.dataset.onboardingId=onboarding.id;
    const heading=canonicalText(document.createElement("h2"),onboarding.title,"onboarding.title");heading.id=onboarding.id+"_heading";heading.tabIndex=-1;
    const introduction=document.createElement("div");introduction.className="home-introduction";
    appendCanonicalParagraph(introduction,onboarding.introduction.summary,"onboarding.introduction.summary");
    appendCanonicalParagraph(introduction,onboarding.introduction.no_psi_note,"onboarding.introduction.no_psi_note","home-key-point");
    appendCanonicalParagraph(introduction,onboarding.introduction.orientation,"onboarding.introduction.orientation");guide.append(heading,introduction);
    const primary=document.createElement("ul");primary.className="home-primary-paths";
    onboarding.primary_paths.forEach((link:any,index:number)=>{const item=document.createElement("li");item.className="home-card";item.append(destinationControl(link,`onboarding.primary_paths.${index}`));if(link.description)appendCanonicalParagraph(item,link.description,`onboarding.primary_paths.${index}.description`,"home-card__description");primary.append(item);});guide.append(primary);
    const disciplines=homeSection(onboarding.disciplines,"onboarding.disciplines"),disciplineCards=document.createElement("ul");disciplineCards.className="home-card-list";
    onboarding.disciplines.cards.forEach((link:any,index:number)=>{const card=document.createElement("li");card.className="home-card";const title=document.createElement("h4");title.className="home-card__title";title.append(destinationControl(link,`onboarding.disciplines.cards.${index}`));card.append(title);if(link.description)appendCanonicalParagraph(card,link.description,`onboarding.disciplines.cards.${index}.description`,"home-card__description");disciplineCards.append(card);});disciplines.append(disciplineCards);guide.append(disciplines);
    const basic=homeSection(onboarding.basic_turn,"onboarding.basic_turn"),steps=document.createElement("ol");
    onboarding.basic_turn.steps.forEach((text:string,index:number)=>{const item=canonicalText(document.createElement("li"),text,`onboarding.basic_turn.steps.${index}`);steps.append(item);});basic.append(steps);
    const reminders=document.createElement("ul");onboarding.basic_turn.reminders.forEach((text:string,index:number)=>{const item=canonicalText(document.createElement("li"),text,`onboarding.basic_turn.reminders.${index}`);reminders.append(item);});basic.append(reminders);
    appendDestinationList(basic,onboarding.basic_turn.destinations,"onboarding.basic_turn.destinations");guide.append(basic);
    const build=homeSection(onboarding.build_checklist,"onboarding.build_checklist"),checklist=document.createElement("ol");checklist.className="home-checklist";
    onboarding.build_checklist.items.forEach((link:any,index:number)=>{const item=document.createElement("li");item.append(destinationControl(link,`onboarding.build_checklist.items.${index}`));checklist.append(item);});build.append(checklist);guide.append(build);
    const glossary=homeSection(onboarding.glossary,"onboarding.glossary"),definitions=document.createElement("dl");definitions.className="home-glossary";
    onboarding.glossary.entries.forEach((entry:any,index:number)=>{const term=document.createElement("dt");term.append(destinationControl(entry,`onboarding.glossary.entries.${index}`));const definition=canonicalText(document.createElement("dd"),entry.definition,`onboarding.glossary.entries.${index}.definition`);definitions.append(term,definition);});glossary.append(definitions);guide.append(glossary);
    const next=homeSection(onboarding.next_destinations,"onboarding.next_destinations");appendDestinationList(next,onboarding.next_destinations.items,"onboarding.next_destinations.items");guide.append(next);
    root.append(guide);if(focusPage)focusHeading(heading);
  }
  type CalculatorTerms={dice:Array<{count:number;sides:number}>;flat:number};
  const calculatorBandValue=(bands:any[],level:number):number=>Number(bands.find((band:any)=>level>=band.minimum_level&&level<=band.maximum_level)?.value??0);
  const calculatorTierMinimum=(tier:number):number=>Number(calculator.tier_minimum_levels.find((item:any)=>item.tier===tier)?.minimum_level??calculator.fighter_level_minimum);
  const calculatorSelectionAvailable=(selection:string,level=state.fighterLevel):boolean=>selection==="common_manifested_strike"||Boolean(calculatorFeatures.has(selection)&&Number(entities.get(selection)?.level)<=level);
  const calculatorValues=()=>{const proficiencyBonus=calculatorBandValue(calculator.proficiency_bonus_bands,state.fighterLevel),totalPsiPoints=calculatorBandValue(calculator.psi_point_bands,state.fighterLevel),psionicFocus=calculatorBandValue(calculator.psionic_focus_bands,state.fighterLevel),strikeSides=calculatorBandValue(calculator.manifested_strike_die_bands,state.fighterLevel),attackBonus=proficiencyBonus+state.psiModifier+psionicFocus,saveDc=8+proficiencyBonus+state.psiModifier;return{proficiencyBonus,totalPsiPoints,psionicFocus,strikeSides,attackBonus,saveDc,strike:{dice:[{count:1,sides:strikeSides}],flat:state.psiModifier} as CalculatorTerms};};
  const calculatorDamageTerms=(damage:any,strikeSides:number):CalculatorTerms=>{if(damage.kind==="fixed")return{dice:[],flat:damage.value};if(damage.kind==="dice")return{dice:[{count:damage.count,sides:damage.sides}],flat:0};if(damage.kind==="manifested_strike_dice")return{dice:[{count:damage.count,sides:strikeSides}],flat:0};if(damage.kind==="psionic_ability_modifier")return{dice:[],flat:state.psiModifier*Number(damage.multiplier??1)};return{dice:[],flat:0};};
  const combineCalculatorTerms=(...values:CalculatorTerms[]):CalculatorTerms=>({dice:values.flatMap(value=>value.dice),flat:values.reduce((total,value)=>total+value.flat,0)});
  function formatCalculatorDamage(terms:CalculatorTerms):string {const dice=new Map<number,number>();for(const term of terms.dice)dice.set(term.sides,(dice.get(term.sides)??0)+term.count);const expression=[...dice].map(([sides,count])=>`${count}d${sides}`).join(" + ");if(!expression)return String(terms.flat);if(terms.flat===0)return expression;return `${expression} ${terms.flat<0?"-":"+"} ${Math.abs(terms.flat)}`;}
  const calculatorHitCalculation=(values:ReturnType<typeof calculatorValues>):string=>`1d20 + Proficiency Bonus (${values.proficiencyBonus}) + Psionic Ability Modifier (${state.psiModifier}) + Psionic Focus (${values.psionicFocus}) = 1d20 + ${values.attackBonus}`;
  const calculatorDamageCalculation=(values:ReturnType<typeof calculatorValues>):string=>`Manifested Strike die (1d${values.strikeSides}) + Psionic Ability Modifier (${state.psiModifier}) = ${formatCalculatorDamage(values.strike)}`;
  const calculatorSaveCalculation=(values:ReturnType<typeof calculatorValues>):string=>`8 + Proficiency Bonus (${values.proficiencyBonus}) + Psionic Ability Modifier (${state.psiModifier}) = ${values.saveDc}`;
  const calculatorAverage=(terms:CalculatorTerms):number=>terms.dice.reduce((total,term)=>total+term.count*(term.sides+1)/2,terms.flat);
  function calculatorHalfAverage(terms:CalculatorTerms):number {let distribution=new Map<number,number>([[0,1]]);for(const term of terms.dice)for(let die=0;die<term.count;die++){const next=new Map<number,number>();for(const [total,count] of distribution)for(let face=1;face<=term.sides;face++)next.set(total+face,(next.get(total+face)??0)+count);distribution=next;}let weighted=0,outcomes=0;for(const [total,count] of distribution){weighted+=Math.max(0,Math.floor((total+terms.flat)/2))*count;outcomes+=count;}return outcomes?weighted/outcomes:Math.max(0,Math.floor(terms.flat/2));}
  const formatCalculatorNumber=(value:number):string=>String(value);
  function appendCalculatorMetric(parent:HTMLElement,label:string,value:string,className?:string):HTMLParagraphElement {const paragraph=document.createElement("p");if(className)paragraph.className=className;const strong=document.createElement("strong");strong.textContent=`${label}:`;paragraph.append(strong,document.createTextNode(` ${value}`));parent.append(paragraph);return paragraph;}
  function appendCalculatorSaveCalculation(parent:HTMLElement,values:ReturnType<typeof calculatorValues>):void {appendCalculatorMetric(parent,String(ui.get("calculator_save_calculation_label")),calculatorSaveCalculation(values),"calculator__calculation calculator__save-calculation");}
  function appendCalculatorStrike(parent:HTMLElement,headingLevel:"h3"|"h4",headingText:string,includeSaveDc:boolean):void {const values=calculatorValues(),heading=document.createElement(headingLevel);heading.textContent=headingText;parent.append(heading);appendCalculatorMetric(parent,String(ui.get("calculator_hit_label")),`1d20 + ${values.attackBonus}`);appendCalculatorMetric(parent,String(ui.get("calculator_hit_breakdown_label")),calculatorHitCalculation(values),"calculator__calculation calculator__breakdown");appendCalculatorMetric(parent,String(ui.get("calculator_damage_label")),formatCalculatorDamage(values.strike));appendCalculatorMetric(parent,String(ui.get("calculator_damage_breakdown_label")),calculatorDamageCalculation(values),"calculator__calculation calculator__breakdown");appendCalculatorMetric(parent,String(ui.get("calculator_expected_average_label")),formatCalculatorNumber(calculatorAverage(values.strike)));if(includeSaveDc){appendCalculatorMetric(parent,String(ui.get("calculator_psionic_save_dc_label")),String(values.saveDc));appendCalculatorSaveCalculation(parent,values);}}
  const calculatorTierPrefix=/^T([012]) (?:Base|Overload):(?: Changes from Tier [01]:)?\s*/;
  const calculatorDeltaPrefix=/^Changes from Tier [01]:\s*/;
  type CalculatorRuleBlock={type:"paragraph";text:string;path:string}|{type:"list";style:"ordered"|"unordered";items:Array<{inlines:any[];path:string}>};
  function calculatorNestedRuleBlock(block:any,path:string,stripDelta:boolean):CalculatorRuleBlock[]{
    if(block.type==="paragraph"){
      const text=inlineText(block.inlines).replace(stripDelta?calculatorDeltaPrefix:/^$/,"");
      return text?[{type:"paragraph",text,path}]:[];
    }
    if(block.type==="list"){
      const items=block.items.map((inlines:any[],index:number)=>({inlines,path:`${path}.items.${index}`}));
      return items.length?[{type:"list",style:block.style,items}]:[];
    }
    if(block.body)return block.body.flatMap((child:any,index:number)=>calculatorNestedRuleBlock(child,`${path}.body.${index}`,stripDelta));
    return[];
  }
  function calculatorRuleBlocks(entity:any,tier?:number):CalculatorRuleBlock[]{
    const result:CalculatorRuleBlock[]=[];let inferredTier:number|undefined;
    for(const [index,block] of entity.content.entries()){
      const path=`entities.${entity.id}.content.${index}`;
      if(block.type==="tier"){inferredTier=undefined;if(tier!==undefined&&Number(block.tier)===tier)result.push(...block.body.flatMap((child:any,childIndex:number)=>calculatorNestedRuleBlock(child,`${path}.body.${childIndex}`,true)));continue;}
      if(block.type==="paragraph"){
        const text=inlineText(block.inlines),match=text.match(calculatorTierPrefix);
        if(match){inferredTier=Number(match[1]);if(tier===inferredTier){const value=text.slice(match[0].length);if(value)result.push({type:"paragraph",text:value,path});}}
        else{inferredTier=undefined;if(tier===undefined)result.push({type:"paragraph",text,path});}
        continue;
      }
      if(block.type==="list"){if(tier===undefined?inferredTier===undefined:inferredTier===tier)result.push(...calculatorNestedRuleBlock(block,path,false));continue;}
      inferredTier=undefined;
    }
    return result;
  }
  function appendCalculatorRuleBlock(parent:HTMLElement,block:CalculatorRuleBlock):void {if(block.type==="paragraph"){const paragraph=document.createElement("p");paragraph.textContent=block.text;paragraph.dataset.sourcePath=block.path;parent.append(paragraph);return;}const list=document.createElement(block.style==="ordered"?"ol":"ul");for(const item of block.items){const li=document.createElement("li");for(const inline of item.inlines)appendInline(li,inline);li.dataset.sourcePath=item.path;list.append(li);}parent.append(list);}
  const calculatorTierScope=(tiers:number[]):string=>tiers.length===1?`Tier ${tiers[0]}`:tiers.every((tier,index)=>index===0||tier===tiers[index-1]!+1)?`Tiers ${tiers[0]}–${tiers[tiers.length-1]}`:`Tiers ${tiers.join(", ")}`;
  function appendCalculatorFeatureDetails(parent:HTMLElement,entity:any,feature:any,values:ReturnType<typeof calculatorValues>):void {const details=document.createElement("section");details.className="calculator__facts";details.setAttribute("aria-label",String(ui.get("calculator_feature_details_label")));appendCalculatorMetric(details,String(ui.get("calculator_psi_cost_label")),String(entity.psi_cost));appendCalculatorMetric(details,String(ui.get("calculator_total_psi_points_label")),String(values.totalPsiPoints));const saveGroups=new Map<string,number[]>();for(const tier of feature.tiers)if(tier.save){const tiers=saveGroups.get(tier.save)??[];tiers.push(Number(tier.tier));saveGroups.set(tier.save,tiers);}if(!saveGroups.size){const noSave=document.createElement("p");noSave.className="calculator__no-save";noSave.textContent=String(ui.get("calculator_no_tier_save"));details.append(noSave);}else{const groups=document.createElement("div");groups.className="calculator__save-groups";for(const [save,rawTiers] of saveGroups){const tiers=[...rawTiers].sort((a,b)=>a-b),group=document.createElement("div");group.className="calculator__save-group";const saveMetric=appendCalculatorMetric(group,String(ui.get(`calculator_${save}_save_label`)),`DC ${values.saveDc}`,"calculator__save");saveMetric.dataset.saveTiers=tiers.join(" ");appendCalculatorSaveCalculation(group,values);const scope=document.createElement("p");scope.className="calculator__save-scope";scope.textContent=String(ui.get("calculator_save_scope")).replace("{tiers}",calculatorTierScope(tiers));group.append(scope);groups.append(group);}details.append(groups);}parent.append(details);}
  function appendCalculatorSharedRules(parent:HTMLElement,entity:any):void {const blocks=calculatorRuleBlocks(entity);if(!blocks.length)return;const shared=document.createElement("section");shared.className="calculator__shared-effects";const heading=document.createElement("h4");heading.textContent=String(ui.get("calculator_shared_rules_heading"));shared.append(heading);for(const block of blocks)appendCalculatorRuleBlock(shared,block);parent.append(shared);}
  function calculatorDamageOutcome(damage:any,values:ReturnType<typeof calculatorValues>):{damage:string;average:string} {const terms=calculatorDamageTerms(damage,values.strikeSides),expression=formatCalculatorDamage(terms),average=calculatorAverage(terms);if(damage.resolution==="failed_save")return{damage:`${expression} on a failed save · 0 on a successful save`,average:`${formatCalculatorNumber(average)} on a failed save · 0 on a successful save`};if(damage.resolution==="half_on_success")return{damage:`${expression} on a failed save · half on a successful save`,average:`${formatCalculatorNumber(average)} on a failed save · ${formatCalculatorNumber(calculatorHalfAverage(terms))} on a successful save`};return{damage:expression,average:formatCalculatorNumber(average)};}
  function appendCalculatorRiderTierMetrics(metrics:HTMLElement,tier:any,values:ReturnType<typeof calculatorValues>):void {const riderTerms=calculatorDamageTerms(tier.damage,values.strikeSides),combinedTerms=combineCalculatorTerms(values.strike,riderTerms),riderExpression=formatCalculatorDamage(riderTerms),combinedExpression=formatCalculatorDamage(combinedTerms),combinedAverage=calculatorAverage(combinedTerms);let riderDamage=riderExpression,combinedDamage=combinedExpression,expectedCombined=formatCalculatorNumber(combinedAverage);if(tier.damage.resolution==="failed_save"){riderDamage=`${riderExpression} on a failed save · 0 on a successful save`;combinedDamage=`${combinedExpression} on a failed save · ${formatCalculatorDamage(values.strike)} on a successful save`;expectedCombined=`${formatCalculatorNumber(combinedAverage)} on a failed save · ${formatCalculatorNumber(calculatorAverage(values.strike))} on a successful save`;}else if(tier.damage.resolution==="half_on_success"){const halfAverage=calculatorHalfAverage(riderTerms);riderDamage=`${riderExpression} on a failed save · half on a successful save`;combinedDamage=`${combinedExpression} on a failed save · ${formatCalculatorDamage(values.strike)} + half of ${riderExpression} on a successful save`;expectedCombined=`${formatCalculatorNumber(combinedAverage)} on a failed save · ${formatCalculatorNumber(calculatorAverage(values.strike)+halfAverage)} on a successful save`;}appendCalculatorMetric(metrics,String(ui.get("calculator_rider_damage_label")),riderDamage);appendCalculatorMetric(metrics,String(ui.get("calculator_combined_damage_label")),combinedDamage);appendCalculatorMetric(metrics,String(ui.get("calculator_expected_combined_average_label")),expectedCombined);}
  function appendCalculatorStandaloneTierMetrics(metrics:HTMLElement,tier:any,values:ReturnType<typeof calculatorValues>):void {const primary=tier.damage.kind==="none"?null:calculatorDamageOutcome(tier.damage,values),secondary=tier.secondary_damage&&tier.secondary_damage.kind!=="none"?calculatorDamageOutcome(tier.secondary_damage,values):null;if(primary){appendCalculatorMetric(metrics,String(ui.get(secondary?"calculator_primary_target_damage_label":"calculator_damage_label")),primary.damage);appendCalculatorMetric(metrics,String(ui.get(secondary?"calculator_expected_primary_target_average_label":"calculator_expected_average_label")),primary.average);}if(secondary){appendCalculatorMetric(metrics,String(ui.get("calculator_secondary_target_damage_label")),secondary.damage);appendCalculatorMetric(metrics,String(ui.get("calculator_expected_secondary_target_average_label")),secondary.average);}}
  function appendCalculatorTier(parent:HTMLElement,entity:any,feature:any,tier:any,values:ReturnType<typeof calculatorValues>):void {const section=document.createElement("section");section.className="calculator__tier";section.dataset.tier=String(tier.tier);const minimumLevel=Math.max(Number(entity.level),calculatorTierMinimum(tier.tier)),available=state.fighterLevel>=minimumLevel;section.dataset.available=String(available);const heading=document.createElement("h4");heading.textContent=`Tier ${tier.tier}`;section.append(heading);if(!available){const availability=document.createElement("p");availability.className="calculator__availability";availability.setAttribute("role","status");availability.textContent=String(ui.get("calculator_tier_available_at_level")).replace("{level}",String(minimumLevel));section.append(availability);}
    const metrics=document.createElement("div");metrics.className="calculator__metrics";if(feature.delivery==="on_hit_rider")appendCalculatorRiderTierMetrics(metrics,tier,values);else appendCalculatorStandaloneTierMetrics(metrics,tier,values);const bloodTax=tier.tier===0?0:values.proficiencyBonus*tier.tier;appendCalculatorMetric(metrics,String(ui.get("calculator_blood_tax_label")),String(bloodTax));section.append(metrics);
    const effects=document.createElement("section");effects.className="calculator__effects";effects.setAttribute("aria-label",String(ui.get("calculator_target_effect_label")));for(const block of calculatorRuleBlocks(entity,tier.tier))appendCalculatorRuleBlock(effects,block);section.append(effects);parent.append(section);}
  function updateCalculator():void {const results=get("calculator-feature-results");results.textContent="";results.hidden=false;if(state.calculatorSelection==="common_manifested_strike"){appendCalculatorStrike(results,"h3",String(ui.get("calculator_manifested_strike_heading")),true);return;}const feature=calculatorFeatures.get(state.calculatorSelection),entity=entities.get(state.calculatorSelection);if(!feature||!entity){results.hidden=true;return;}const heading=document.createElement("h3");heading.textContent=entity.title;results.append(heading);if(feature.delivery==="on_hit_rider"){const trigger=document.createElement("section");trigger.className="calculator__trigger";appendCalculatorStrike(trigger,"h4",String(ui.get("calculator_triggering_strike_heading")),false);results.append(trigger);}const values=calculatorValues();appendCalculatorFeatureDetails(results,entity,feature,values);appendCalculatorSharedRules(results,entity);const tiers=document.createElement("div");tiers.className="calculator__tiers";for(const tier of [...feature.tiers].sort((a:any,b:any)=>a.tier-b.tier))appendCalculatorTier(tiers,entity,feature,tier,values);results.append(tiers);}
  function syncCalculatorAvailability(select:HTMLSelectElement):void {for(const option of [...select.options])option.disabled=Number(option.dataset.minimumLevel??calculator.fighter_level_minimum)>state.fighterLevel;if(!calculatorSelectionAvailable(state.calculatorSelection))state.calculatorSelection="common_manifested_strike";select.value=state.calculatorSelection;}
  function renderCalculator(focusPage=false):void {syncViewChrome();const publicationRoot=get("rules-content");publicationRoot.textContent="";const root=document.createElement("div");root.id="calculator-root";root.className="calculator";const heading=document.createElement("h2");heading.id="calculator-heading";heading.tabIndex=-1;heading.textContent=String(ui.get("calculator_heading"));
    const controlPanel=document.createElement("section");controlPanel.className="panel";const controlsHeading=document.createElement("h3");controlsHeading.id="calculator-controls-heading";controlsHeading.className="sr-only";controlsHeading.textContent=String(ui.get("calculator_controls_heading"));const controls=document.createElement("div");controls.className="calculator__controls";
    const field=(id:string,labelText:string)=>{const label=document.createElement("label");label.className="field";label.htmlFor=id;label.append(document.createTextNode(labelText));const select=document.createElement("select");select.id=id;select.setAttribute("aria-controls","calculator-feature-results");label.append(select);controls.append(label);return select;};
    const feature=field("calculator-feature",String(ui.get("calculator_feature_label"))),level=field("calculator-level",String(ui.get("calculator_level_label"))),modifier=field("calculator-psi-modifier",String(ui.get("calculator_modifier_label")));const baseline=document.createElement("option");baseline.value="common_manifested_strike";baseline.textContent=entities.get("common_manifested_strike")?.title??String(ui.get("calculator_manifested_strike_heading"));baseline.dataset.minimumLevel=String(calculator.fighter_level_minimum);feature.append(baseline);
    for(const area of [...areaValues].sort((a:any,b:any)=>a.order-b.order)){const features=calculator.features.filter((item:any)=>entities.get(item.entity_id)?.presentation_metadata.primary_rules_area===area.id).sort((a:any,b:any)=>{const left=entities.get(a.entity_id),right=entities.get(b.entity_id);return Number(left?.level)-Number(right?.level)||String(left?.title).localeCompare(String(right?.title));});if(!features.length)continue;const group=document.createElement("optgroup");group.label=area.label;for(const item of features){const entity=entities.get(item.entity_id),option=document.createElement("option");option.value=item.entity_id;option.textContent=entity.title;option.dataset.minimumLevel=String(entity.level);group.append(option);}feature.append(group);}
    for(let value=calculator.fighter_level_minimum;value<=calculator.fighter_level_maximum;value++){const option=document.createElement("option");option.value=String(value);option.textContent=String(value);level.append(option);}for(let value=calculator.psionic_ability_modifier_minimum;value<=calculator.psionic_ability_modifier_maximum;value++){const option=document.createElement("option");option.value=String(value);option.textContent=`+${value}`;modifier.append(option);}level.value=String(state.fighterLevel);modifier.value=String(state.psiModifier);syncCalculatorAvailability(feature);
    feature.addEventListener("change",()=>{state.calculatorSelection=feature.value;updateCalculator();writeHistory("replace");});level.addEventListener("change",()=>{state.fighterLevel=Number(level.value);syncCalculatorAvailability(feature);updateCalculator();writeHistory("replace");});modifier.addEventListener("change",()=>{state.psiModifier=Number(modifier.value);updateCalculator();writeHistory("replace");});controlPanel.append(controlsHeading,controls);const results=document.createElement("section");results.id="calculator-feature-results";results.className="calculator__result";results.setAttribute("aria-live","polite");results.setAttribute("aria-atomic","true");root.append(heading,controlPanel,results);publicationRoot.append(root);updateCalculator();if(focusPage)focusHeading(heading);}
  function renderNameOptions(): void {
    const select=get("name-select") as HTMLSelectElement;select.textContent="";const placeholder=document.createElement("option");placeholder.value="";placeholder.textContent=String(ui.get("name_placeholder"));select.append(placeholder);
    for(const area of model.filterIndex.name_groups){const names=area.entity_ids.map((id:string)=>indexedById.get(id)).filter((item:any)=>item&&match(item));if(!names.length)continue;const group=document.createElement("optgroup");group.label=area.label;for(const item of names){const option=document.createElement("option");option.value=item.id;option.textContent=item.title;group.append(option);}select.append(group);}
    syncNameSelection();
  }
  function readFacetControls(): void {
    for(const facet of model.authority.facets){if(facet.cardinality==="multi")state.classifications[facet.id]=[...document.querySelectorAll(`[data-facet="${facet.id}"]:checked`)].map((node:any)=>node.value);else state.classifications[facet.id]=(get(`facet-${facet.id}`) as HTMLSelectElement).value||"";}
  }
  function renderFacets(): void {
    const root=get("facet-controls");root.textContent="";
    for(const facet of [...model.authority.facets].sort((a:any,b:any)=>a.order-b.order)){const values=model.authority.vocabularies[facet.vocabulary];
      if(facet.cardinality==="multi"){const fieldset=document.createElement("fieldset");const legend=document.createElement("legend");legend.textContent=facet.label;fieldset.append(legend);for(const value of values){const label=document.createElement("label");const input=document.createElement("input");input.type="checkbox";input.value=value.id;input.dataset.facet=facet.id;input.checked=(state.classifications[facet.id]??[]).includes(value.id);label.append(input,document.createTextNode(` ${value.label}`));fieldset.append(label);}root.append(fieldset);}
      else{const label=document.createElement("label");label.className="field";label.htmlFor=`facet-${facet.id}`;label.append(document.createTextNode(facet.label));const select=document.createElement("select");select.id=`facet-${facet.id}`;select.dataset.facet=facet.id;const any=document.createElement("option");any.value="";any.textContent=String(ui.get("any_value"));select.append(any);for(const value of values){const option=document.createElement("option");option.value=value.id;option.textContent=value.label;select.append(option);}select.value=state.classifications[facet.id]??"";label.append(select);root.append(label);}}
  }
  function updateAvailability(): void {
    for(const facet of model.authority.facets){
      if(facet.cardinality==="multi"){const controls=[...document.querySelectorAll(`input[data-facet="${facet.id}"]`)] as HTMLInputElement[];for(const control of controls){const candidate=structuredClone(state.classifications);const active=new Set(candidate[facet.id]??[]);active.add(control.value);candidate[facet.id]=[...active];control.disabled=!control.checked&&!indexed.some((item:any)=>match(item,candidate));}}
      else{const select=get(`facet-${facet.id}`) as HTMLSelectElement;for(const option of [...select.options]){if(!option.value)continue;const candidate=structuredClone(state.classifications);candidate[facet.id]=option.value;option.disabled=option.selected?false:!indexed.some((item:any)=>match(item,candidate));}}
    }
  }
  function renderResults(shouldAnnounce=false): void {
    const root=get("filter-results");root.textContent="";const result=matches();
    if(!result.length){const p=document.createElement("p");p.textContent=String(ui.get("no_matches"));root.append(p);}else{const list=document.createElement("ul");for(const item of result){const li=document.createElement("li");const button=document.createElement("button");const area=areas.get(item.primary_rules_area) as any;const label=String(ui.get("result_identity")).replace("{entity_title}",item.title).replace("{primary_rules_area_label}",area.label);button.textContent=label;button.setAttribute("aria-label",label);button.addEventListener("click",()=>openEntity(item.id,"result"));li.append(button);list.append(li);}if(hasSelections())root.append(list);else{const details=document.createElement("details");details.className="results__all";const summary=document.createElement("summary");summary.textContent=String(ui.get("match_count")).replace("{count}",String(result.length));details.append(summary,list);root.append(details);}}updateAvailability();
    if(shouldAnnounce)announce(result.length===1?String(ui.get("one_match")).replace("{count}",String(result.length)):result.length?String(ui.get("match_count")).replace("{count}",String(result.length)):String(ui.get("no_matches")));
  }
  function resultArea(item:any):string{return item.primary_rules_area;}
  function renderReference(focusEntity?:string,focusMode:"none"|"result"|"mobile"="none"):void {syncViewChrome();renderNavigation();renderNameOptions();renderFacets();renderResults(false);renderTopic(focusEntity,focusMode);}
  function renderView(focusMode:"none"|"home"|"reference"|"calculator"="none"):void {if(state.view==="home")renderHome(focusMode==="home");else if(state.view==="calculator")renderCalculator(focusMode==="calculator");else renderReference(state.entity??undefined,focusMode==="reference"?"result":"none");}
  function openCategory(id:string):void {const target=categories.get(id);if(!target)return;const route=target.default_topic_id;if(state.view==="reference"&&state.category===id&&state.topic===route&&state.entity===null&&!hasSelections())return;state.view="reference";state.category=id;state.topic=route;state.classifications={};state.entity=null;state.resultRoute=null;state.focusOrigin="onboarding";writeHistory("push");renderReference(undefined,"result");}
  function openEntity(id:string,origin:"name"|"result"|"onboarding"):void {
    const item=indexedById.get(id);if(!item)return;const area=origin==="name"?item.primary_rules_area:resultArea(item);const route=item.routes[area];if(state.view==="reference"&&state.entity===id&&state.category===area&&state.topic===route){syncNameSelection();return;}state.view="reference";state.category=area;state.topic=route;state.classifications={};state.entity=id;state.resultRoute=route;state.focusOrigin=origin;writeHistory("push");renderReference(id,origin==="name"?"mobile":"result");if(origin==="name")announce(String(ui.get("filter_cleared")));
  }
  function openHome():void {if(state.view==="home")return;state.view="home";state.focusOrigin="view";writeHistory("push");renderHome(true);}
  function openReference():void {if(state.view==="reference")return;state.view="reference";state.focusOrigin="view";writeHistory("push");renderReference(state.entity??undefined,"result");}
  function openCalculator():void {if(state.view==="calculator")return;state.view="calculator";state.focusOrigin="view";writeHistory("push");renderCalculator(true);}
  function parseFragment():boolean {
    let corrected=false;const raw=location.hash.slice(1);state.focusOrigin="fragment";state.classifications={};state.entity=null;state.resultRoute=null;
    if(raw===""||raw===homeFragment){state.view="home";normalizeNavigation(model.authority.navigation.default_category_id,defaultTopic(model.authority.navigation.default_category_id));return false;}
    if(raw===calculatorFragment){state.view="calculator";normalizeNavigation(model.authority.navigation.default_category_id,defaultTopic(model.authority.navigation.default_category_id));return false;}
    state.view="reference";const parameters=new URLSearchParams(raw),requestedCategory=parameters.get("category"),requestedTopic=parameters.get("topic");if(normalizeNavigation(requestedCategory,requestedTopic))corrected=true;
    const filters=parameters.get("filters");if(filters)for(const pair of filters.split(";")){const [facetId,rawValue]=pair.split(":");if(!facetId||!rawValue){corrected=true;continue;}const facet=model.authority.facets.find((candidate:any)=>candidate.id===facetId);if(!facet){corrected=true;continue;}const allowed=new Set(model.authority.vocabularies[facet.vocabulary].map((value:any)=>value.id));const values=[...new Set<string>(rawValue.split(",").filter((value:string)=>allowed.has(value)))];if(!values.length){corrected=true;continue;}state.classifications[facetId]=facet.cardinality==="multi"?values.slice(0,allowed.size):values[0];}
    const entityId=parameters.get("entity");if(entityId&&entities.has(entityId)){state.entity=entityId;const currentTopic=topic();if(!currentTopic.entity_ids.includes(entityId)){const item=indexedById.get(entityId);state.category=item.primary_rules_area;state.topic=item.routes[item.primary_rules_area];state.classifications={};corrected=true;}state.resultRoute=state.topic;}else if(entityId)corrected=true;return corrected;
  }
  function classificationsAreValid(value:any):boolean {
    if(!value||typeof value!=="object"||Array.isArray(value))return false;
    return Object.entries(value).every(([id,selection]:any)=>{
      const facet=model.authority.facets.find((candidate:any)=>candidate.id===id);
      if(!facet)return false;
      const allowed=new Set<string>(model.authority.vocabularies[facet.vocabulary].map((item:any)=>item.id));
      if(facet.cardinality==="multi")return Array.isArray(selection)&&selection.length===new Set(selection).size&&selection.every((item:any)=>typeof item==="string"&&allowed.has(item));
      return typeof selection==="string"&&(selection===""||allowed.has(selection));
    });
  }
  function restore(snapshot:any):void {
    const candidate=snapshot&&typeof snapshot==="object"?{calculatorSelection:defaultCalculatorSelection,fighterLevel:calculator.default_fighter_level,psiModifier:calculator.default_psionic_ability_modifier,...snapshot}:snapshot;
    const fields=new Set(model.policy.history_state_fields),keys=Object.keys(candidate??{}),validFields=keys.length===fields.size&&keys.every(key=>fields.has(key)),validView=model.policy.application_views.includes(candidate?.view),validFilters=classificationsAreValid(candidate?.classifications),validFocus=model.policy.focus_origins.includes(candidate?.focusOrigin),validEntity=candidate?.entity===null||entities.has(candidate?.entity),validResultRoute=candidate?.entity===null?candidate?.resultRoute===null:typeof candidate?.resultRoute==="string"&&candidate.resultRoute===candidate.topic,validLevel=Number.isInteger(candidate?.fighterLevel)&&candidate.fighterLevel>=calculator.fighter_level_minimum&&candidate.fighterLevel<=calculator.fighter_level_maximum,validModifier=Number.isInteger(candidate?.psiModifier)&&candidate.psiModifier>=calculator.psionic_ability_modifier_minimum&&candidate.psiModifier<=calculator.psionic_ability_modifier_maximum,validCalculator=typeof candidate?.calculatorSelection==="string"&&calculatorSelectionAvailable(candidate.calculatorSelection,candidate.fighterLevel);
    if(!candidate||!validFields||!validView||!validFilters||!validFocus||!validEntity||!validResultRoute||!validLevel||!validModifier||!validCalculator){initialize();return;}Object.assign(state,candidate);const corrected=normalizeNavigation();renderView();if(corrected)writeHistory("replace");
  }
  function initialize():void {const corrected=parseFragment();renderView();writeHistory("replace");if(corrected&&state.view==="reference")announce(String(ui.get("filter_instruction")));}
  get("category-select").addEventListener("change",event=>{normalizeNavigation((event.target as HTMLSelectElement).value,"");state.entity=null;state.resultRoute=null;state.focusOrigin="category";syncNameSelection();renderNavigation();renderTopic(undefined,"mobile");writeHistory("push");syncViewChrome();announce(category().label);});
  get("topic-select").addEventListener("change",event=>{normalizeNavigation(state.category,(event.target as HTMLSelectElement).value);state.entity=null;state.resultRoute=null;state.focusOrigin="topic";syncNameSelection();renderTopic(undefined,"mobile");writeHistory("push");syncViewChrome();announce(topic()?.title??category().label);});
  get("name-select").addEventListener("change",event=>openEntity((event.target as HTMLSelectElement).value,"name"));
  get("facet-controls").addEventListener("change",()=>{readFacetControls();state.entity=null;state.resultRoute=null;state.focusOrigin="result";renderNameOptions();writeHistory("push");syncViewChrome();renderResults(true);});
  document.querySelector<HTMLAnchorElement>(".skip")!.addEventListener("click",event=>{if(!ordinaryActivation(event))return;event.preventDefault();const content=get("rules-content");content.focus({preventScroll:true});content.scrollIntoView({block:"start"});});
  get("view-start-here").addEventListener("click",event=>{if(!ordinaryActivation(event))return;event.preventDefault();openHome();});
  get("view-rules-reference").addEventListener("click",event=>{if(!ordinaryActivation(event))return;event.preventDefault();openReference();});
  get("view-calculator").addEventListener("click",event=>{if(!ordinaryActivation(event))return;event.preventDefault();openCalculator();});
  addEventListener("popstate",event=>restore(event.state));initialize();
}
